import WorkData from "@/basics/WorkData";

export const WorkNotFound = new WorkData(
    404,
    false,
    false,
    "404",
    "404",
    "",
    "",
    "",
    "",
    [],
    "",
    "",
    "",
    "",
    [],
    "",
);

export const Iremi = new WorkData(
    20230318,
    true,
    true,
    "Iremi",
    "iremi",
    "I developed this app entirely on my own, and it offers users a range of breathing exercises that are specifically designed to ",
    "promote relaxation and mindfulness.",
    "Mobile App",
    "https://i.imgur.com/eoEx6Tt.png?1",
    [
        "Flutter",
        "Dart",
        "Firebase",
    ],
    "Iremi is a mobile app designed to help users ",
    "combat anxiety through guided breathing exercises. ",
    "Using Flutter and Dart, I have created a simple and intuitive app that offers a variety of breathing exercises tailored to he users' needs. \nThe app also includes a progress tracker that allows users to monitor their breathing habits and ",
    "track their progress over time.",
    [""],
    "https://github.com/ZiClaud/Iremi-Breathing-App",
);

export const JEIOM = new WorkData(
    20220614,
    true,
    false,
    "JEIOM23",
    "jeiom",
    "I was part of a team that developed this website for the JEIOM 2023 event. Our goal was to create a platform that would enable users to ",
    "organize their schedule for the event in a single, user-friendly interface",
    "Website",
    "https://i.imgur.com/nu9WG4d.png",
    [
        "React",
        "TailwindCSS",
        "NodeJS",
    ],
    "JEIOM23 is a dynamic website designed specifically for the JEIOM 2023 event. It provides users with convenient access to the",
    "event's schedule, comprehensive information about the event itself, and recommendations on must-see attractions and experiences.\n",
    "Our dedicated team utilized a powerful tech stack comprising React, TailwindCSS, and NodeJS to develop this feature-rich website, ensuring a",
    "seamless and immersive user experience.",
    [""],
    "www.jeiom23.com",
);

export const ReactTest2 = new WorkData(
    20230601,
    true,
    false,
    "React 2",
    "react2",
    "...",
    "...",
    "Website",
    "https://i.imgur.com/TXE0NFx.png",
    [
        "React",
        "TailwindCSS",
    ],
    "",
    "",
    "",
    "",
    [""],
    "https://github.com/ZiClaud/nextjs-tailwindcss-template",
);

export const ReactTest1 = new WorkData(
    20220528,
    true,
    false,
    "React 1",
    "react1",
    "...",
    "...",
    "Website",
    "https://i.imgur.com/8AXClU0.png",
    [
        "React",
        "TailwindCSS",
    ],
    "",
    "",
    "",
    "",
    [""],
    "https://github.com/EscanorTargaryen/dash2",
);

export const Portfolio = new WorkData(
    20230426,
    true,
    true,
    "This Portfolio",
    "portfolio",
    "I developed this portfolio, taking inspiration from a design found online, created first in ",
    "Flutter, then recreated in React.",
    "Website",
    "https://i.imgur.com/5yosKhp.png",
    [
        "React",
        "TailwindCSS",
        "NodeJS",
        "Flutter",
        "Dart",
    ],
    "",
    "",
    "",
    "",
    [""],
    "https://claudiodimaioflutter.netlify.app/",
);

export const JEMOREApp = new WorkData(
    20220727,
    false,
    false,
    "JEMORE App",
    "jemore_app",
    "Application ...",
    "",
    "Mobile App",
    "https://i.imgur.com/WrD3akd.png",
    [
        "Flutter",
        "Dart",
        "Parse",
    ],
    "",
    "",
    "",
    "",
    [""],
    "https://play.google.com/store/apps/details?id=it.jemore.jemore_services",
);

export const JEMORETreasury = new WorkData(
    20220803,
    false,
    false,
    "JEMORE Treasury",
    "jemore_treasury",
    "Website ...",
    "",
    "Website",
    "https://i.imgur.com/NpWRniN.png",
    [
        "Flutter",
        "Dart",
    ],
    "",
    "",
    "",
    "",
    [""],
    undefined,
);

export const SQLServerDatabase = new WorkData(
    0,
    false,
    false,
    "SQL Server Database",
    "sql_database",
    "Database ...",
    "",
    "Database",
    "https://i.imgur.com/l9hWzLi.png",
    ["SQL Server"],
    "",
    "",
    "",
    "",
    [""], undefined,
);

export const ChessSoftware = new WorkData(
    0,
    false,
    false,
    "Chess Software",
    "chess",
    "Desktop App that...",
    "",
    "Desktop Game",
    "https://i.imgur.com/BfPrqrh.png",
    ["Java"],
    "",
    "",
    "",
    "",
    [""],
    "https://github.com/ZiClaud/Chess",
);

export const FightingGame = new WorkData(
    0,
    false,
    false,
    "Fighting Game",
    "fighting_game",
    "Desktop Game that...",
    "",
    "Desktop Game",
    "https://i.imgur.com/3fQrf61.png",
    ["Java"],
    "An adrenaline-pumping adventure that marks my first foray into the world of game development using Java. Embrace the thrill as you step into the virtual arena, engaging in intense battles with ",
    "computer-controlled opponents. ",
    "Armed with Java's power and flexibility, I crafted this game with passion and determination, learning valuable lessons in ",
    "game mechanics, graphics rendering, and user interaction.",
    [""],
    "https://github.com/ZiClaud/FightingGame",
);

export const PickyEater = new WorkData(
    0,
    false,
    false,
    "Picky Eater",
    "picky_eater",
    "Desktop App that...",
    "",
    "Desktop App",
    "https://i.imgur.com/ILeeONf.png",
    ["Java"],
    "A collaborative masterpiece and a memorable university project. Teaming up with Federico Matarante, we embarked on a journey into the realm of Java programming and Object-Oriented Programming (OOP). This Desktop Application ",
    "was designed to cater to picky eaters, offering personalized meal recommendations based on individual preferences and dietary restrictions. ",
    "Through Picky Eater, I gained valuable insights into the power of OOP, mastering the art of creating robust and scalable code. ",
    "",
    [""],
    "https://github.com/ZiClaud/PickyEaterApp",
);

export const OldPortfolio = new WorkData(
    0,
    false,
    false,
    "Old Portfolio",
    "old_portfolio",
    "Website ...",
    "",
    "Website",
    "https://i.imgur.com/dA288Wb.png",
    [
        "HTML",
        "CSS",
        "JavaScript",
    ],
    "A significant milestone in my journey as a developer. It marks my first venture into the world of web development, ",
    "where I designed and crafted an online portfolio from scratch ",
    "using HTML, JavaScript, and CSS. Take a trip down memory lane and witness my initial steps in the dynamic world of web development with my old Portfolio.",
    "",
    [""],
    "https://claudiodimaioold.netlify.app/",
);

export const HangmanGame = new WorkData(
    20201204,
    false,
    false,
    "Hangman Game",
    "hangman",
    "Command line game that...",
    "",
    "Command Line Game",
    "https://i.imgur.com/tdtrOVx.png",
    ["C"],
    "Hangman is my debut project. This command-line-based hangman game was crafted ",
    "entirely in C.",
    "It was made using the first programming language I learned.",
    "",
    [""],
    "https://github.com/ZiClaud/Hangman_C",
);


export const AllWorks = [
    Iremi,
    JEIOM,
    Portfolio,
    ReactTest2,
    ReactTest1,
    JEMOREApp,
    JEMORETreasury,
    SQLServerDatabase,
    ChessSoftware,
    FightingGame,
    PickyEater,
    OldPortfolio,
    HangmanGame,
];