import WorkData from "@/basics/WorkData"
import { deprecate } from "util"

// TODO: Create a real database
// TODO: Create an admin page to access that database
export const WorkNotFound = new WorkData(
  404,
  false,
  false,
  "Error 404",
  "404",
  "",
  "",
  "Page not found",
  "",
  [],
  "",
  "",
  "",
  "",
  [],
  undefined,
  undefined,
)

export const WeeksOfMyYear = new WorkData( // TODO
  20260127,
  false,
  false,
  "Weeks of my Year",
  "weeks-of-my-year",
  "...",
  "...",
  "Mobile App Widgets",
  "https://i.imgur.com/TODO.png",
  [
    "Flutter",
    "Dart",
    "Kotlin",
  ],
  "TODO. ",
  "TODO. ",
  "TODO ",
  "TODO.",
  [
    "https://i.imgur.com/TODO.png",
  ],
  "https://github.com/ZiClaud/Weeks-of-my-Year",
  "",
)

export const DrivaliaWebsite = new WorkData(
  20250415,
  false,
  false,
  "Drivalia Website",
  "drivalia-website",
  "...",
  "...",
  "Website Maintainement",
  "https://i.imgur.com/MQNd9kn.png",
  [
    "React",
    "Java",
    "AWS",
  ],
  "A full-stack commercial website developed for Drivalia in collaboration with Deloitte. ",
  "Built and maintained the Drivalia website, handling the frontend in React and contributing to backend features in Java. ",
  "I implemented new features, fixed a high volume of bugs, and eventually became the sole frontend developer on the project. This work also involved my first experience ",
  "deploying and maintaining infrastructure on AWS.",
  [
    "https://i.imgur.com/MQNd9kn.png",
    "https://i.imgur.com/Z1liUpY.png",
  ],
  "https://www.drivalia.com/eng/corporate",
  "https://avatars.githubusercontent.com/u/167996808",
)

export const LupusAmongUs = new WorkData( // TODO
  20250311,
  false,
  false,
  "Lupus Among Us",
  "lupus-among-us",
  "...",
  "...",
  "Web Game",
  "",
  [
    "Godot",
  ],
  "My first 3D multiplayer game, can be played on the web. ",
  "It is inspired by the card game Werewolf. ",
  "The game is made with Godot, a game engine that I love using. ",
  "Play now, by clicking the link below!",
  [],
  undefined,
)

export const MaterialYouNewTab = new WorkData(
  20241014,
  false,
  false,
  "MaterialYouNewTab",
  "material-you-new-tab",
  "...",
  "...",
  "Open Source Contribution",
  "https://i.imgur.com/GL8jbRI.png",
  [
    "CSS",
    "JavaScript",
  ],
  "Contributed to ",
  "MaterialYouNewTab",
  ", a Chrome, FireFox and Safari extension. By fixing the dark theme and adding Italian translation.",
  "",
  [
    "https://i.imgur.com/brPMJox.png",
    "https://i.imgur.com/GL8jbRI.png",
    "https://i.imgur.com/Visy1Nw.png",
    "https://i.imgur.com/m6eOY0r.png",
  ],
  "https://github.com/XengShi/materialYouNewTab",
)

export const Magium = new WorkData(
  20240830,
  false,
  false,
  "Magium",
  "magium",
  "...",
  "...",
  "Open Source Contribution",
  "https://i.imgur.com/BApb3KZ.png",
  [
    "JavaScript",
  ],
  "Contributed to ",
  "Magium",
  ", a fan-made recreation of Christian Mihailescu's text-based adventure. The project ",
  "preserves and expands the original story.",
  [
    "https://i.imgur.com/BApb3KZ.png",
  ],
  "https://github.com/thuiop/magium-dev",
  "https://raw.githubusercontent.com/thuiop/magium-dev/main/public/images/magium.ico",
)

export const SudokuSolver = new WorkData(
  20240807,
  false,
  false,
  "Sudoku Solver",
  "sudoku-solver",
  "...",
  "...",
  "Command Line Program",
  "https://i.imgur.com/vBfZFiH.gif",
  [
    "C",
    "Python",
    "Manim",
  ],
  "Wanted to challenge myself by programming a ",
  "sudoku solver in C",
  ", also created an animation in ",
  "Python using Manim.",
  [
    "https://i.imgur.com/vBfZFiH.gif",
    "https://i.imgur.com/9wmrw5q.gif",
    "https://i.imgur.com/1GamJ02.png",
  ],
  "https://github.com/ZiClaud/Sudoku-Solver",
)

/**
 * @deprecated Project was dropped.
 */
export const InfoWebApp = new WorkData(
  20240804,
  false,
  false,
  "WebApp Community",
  "webapp-community",
  "...",
  "...",
  "Website",
  "",
  [
    "React",
    "TailwindCSS",
    "Vite",
  ],
  "Website made with a group of ",
  "skilled ",
  "programmers.",
  "",
  [
    "",
  ],
  undefined,
)

/**
 * @deprecated Project was dropped.
 */
export const GTEConverter = new WorkData(
  20240628,
  false,
  false,
  "GTE Converter",
  "gte-converter",
  "...",
  "...",
  "Website",
  "",
  [
    "React",
    "TailwindCSS",
    "NodeJS",
  ],
  "Website to convert ChessDotCom links to pgn files, using ",
  "ChessDotCom API",
  ".",
  "",
  [
    "",
  ],
  undefined,
)

export const CosmicGateway = new WorkData(
  20240211,
  false,
  false,
  "Cosmic Gateway",
  "cosmic-gateway",
  "...",
  "...",
  "Desktop & Web Game",
  "https://i.imgur.com/1uT08B1.png",
  [
    "Godot",
  ],
  "My first 'serious' game, can be played on both desktop and web. ",
  "It is a 2D space shooter, where you have to defeat the enemies and reach the end of the level. ",
  "The game is made with Godot, a game engine that I love using. ",
  "Play now, by clicking the link below!",
  [
    // "https://i.imgur.com/mYA6hnz.gif",
    "https://i.imgur.com/1uT08B1.png",
    "https://i.imgur.com/5gGsr4Q.png",
    "https://i.imgur.com/zGXQlHz.png",
  ],
  "https://ziclaud.itch.io/cosmic-gateway",
  "",
)

export const Bookshelf = new WorkData( // TODO
  20230825,
  false,
  false,
  "Bookshelf",
  "bookshelf",
  "...",
  "...",
  "Mobile App",
  "",
  [
    "Flutter",
    "Dart",
    "Firebase",
    "Google API",
  ],
  "",
  "",
  "",
  "",
  [
    "",
  ],
  undefined,
  undefined,
)

export const Iremi = new WorkData(
  20230318,
  true,
  true,
  "Iremi",
  "iremi",
  "I developed this app entirely on my own, and it offers users a range of breathing exercises that are specifically designed to ",
  "promote relaxation and mindfulness.",
  "Mobile App",
  "https://i.imgur.com/eoEx6Tt.png?1",
  [
    "Flutter",
    "Dart",
    "Firebase",
    "SQLite",
  ],
  "Iremi is a mobile app designed to help users ",
  "combat anxiety through guided breathing exercises. ",
  "Using Flutter and Dart, I have created a simple and intuitive app that offers a variety of breathing exercises tailored to he users' needs. \nThe app also includes a progress tracker that allows users to monitor their breathing habits and ",
  "track their progress over time.",
  [
    "https://i.imgur.com/eoEx6Tt.png?1",
    "https://i.imgur.com/zf0f2OA.png",
    "https://i.imgur.com/rzRn7Us.png",
    "https://i.imgur.com/34SF2m0.png",
  ],
  "https://github.com/ZiClaud/Iremi-Breathing-App",
  "https://raw.githubusercontent.com/ZiClaud/Iremi-Breathing-App/refs/heads/master/assets/icon/icon.png",
)

export const JEIOM = new WorkData(
  20220614,
  true,
  false,
  "JEIOM23",
  "jeiom",
  "I was part of a team that developed this website for the JEIOM 2023 event. Our goal was to create a platform that would enable users to ",
  "organize their schedule for the event in a single, user-friendly interface.",
  "Website",
  "https://i.imgur.com/apa36gM.png",
  [
    "React",
    "TailwindCSS",
    "NodeJS",
  ],
  "JEIOM23 is a dynamic website designed specifically for the JEIOM 2023 event. It provides users with convenient access to the ",
  "event's schedule, comprehensive information about the event itself, and recommendations on must-see attractions and experiences. \n",
  "Our dedicated team utilized a powerful tech stack comprising React, TailwindCSS, and NodeJS to develop this feature-rich website, ensuring a ",
  "seamless and immersive user experience.",
  [
    "https://i.imgur.com/apa36gM.png",
    "https://i.imgur.com/86tvggz.png",
    "https://i.imgur.com/FvOm6kL.png",
    "https://i.imgur.com/2lh3ilq.png",
    "https://i.imgur.com/CDk9U5P.png",
    "https://i.imgur.com/WQB2yzk.png",
  ],
  "https://github.com/ZiClaud/JEIOM23",
  "https://raw.githubusercontent.com/ZiClaud/JEIOM23/main/public/logoJeiom.svg",
)

export const ReactTest2 = new WorkData(
  20230601,
  true,
  false,
  "React 2",
  "react2",
  "...",
  "...",
  "Website",
  "https://i.imgur.com/TXE0NFx.png",
  [
    "React",
    "TailwindCSS",
  ],
  "A remarkable solo endeavor that builds upon the foundation laid by my previous project, ",
  "\"React1\". ",
  "As a passionate React developer, I took on the challenge of creating this project independently, delving deeper into the nuances of React and honing my skills further. ",
  "",
  [
    "https://i.imgur.com/TXE0NFx.png",
    "https://i.imgur.com/TwFBzR2.png",
    "https://i.imgur.com/CGMWQYO.png",
    "https://i.imgur.com/Lmnqzw4.png",
  ],
  undefined, //"https://github.com/ZiClaud/Nextjs-Tailwindcss-Template"
)

export const ReactTest1 = new WorkData(
  20220528,
  true,
  false,
  "React 1",
  "react1",
  "...",
  "...",
  "Website",
  "https://i.imgur.com/8AXClU0.png",
  [
    "React",
    "TailwindCSS",
  ],
  "An exciting and collaborative project that marked my debut into the world of React development. Crafted in ",
  "collaboration with a talented group of colleagues, ",
  "this project showcases our collective efforts in harnessing the power of React to build a ",
  "dynamic and interactive web application.",
  [
    "https://i.imgur.com/8AXClU0.png",
    "https://i.imgur.com/wGPTSV3.png",
  ],
  undefined, //"https://github.com/EscanorTargaryen/dash2"
)

export const OpenSource1 = new WorkData(
  20230602,
  false,
  false,
  "Easy Localization",
  "easy-localization",
  "...",
  "...",
  "Open Source Contribution",
  "https://i.imgur.com/MWBvBSE.png",
  [
    "Flutter",
    "Dart",
  ],
  "I entered the world of open source by contributing to the ",
  "\"Easy and Fast internationalization for your Flutter Apps\" repository. ",
  "This impactful endeavor showcases my commitment to improving user experiences and collaborating with the wider development community. ",
  "",
  [
    "https://i.imgur.com/MWBvBSE.png",
  ],
  "https://github.com/aissat/easy_localization/pull/593",
  undefined,
)

export const Portfolio = new WorkData(
  20230426,
  true,
  true,
  "This Portfolio",
  "portfolio",
  "I developed this portfolio, taking inspiration from a design found online, created first in ",
  "Flutter, then recreated in React.",
  "Website",
  "https://i.imgur.com/5yosKhp.png",
  [
    "React",
    "TailwindCSS",
    "NodeJS",
    "Flutter",
    "Dart",
  ],
  "A captivating project that serves as a reflection of my journey as a developer. Inspired by a design discovered online, I took on the challenge of creating my own portfolio, ",
  "first in Flutter and then recreated it in React. ",
  "In the initial phase, I utilized Flutter and its versatile widgets to craft a visually appealing and interactive portfolio. As I honed my skills and explored new technologies, I decided to reimagine the portfolio using React, ",
  "leveraging its component-based architecture and vast ecosystem.",
  [
    "https://i.imgur.com/5yosKhp.png",
    "https://i.imgur.com/HczcJux.png",
    "https://i.imgur.com/K1Nq5G4.png",
  ],
  "https://claudiodimaioflutter.netlify.app/",
  "https://raw.githubusercontent.com/ZiClaud/My-Portfolio-React/main/public/images/ZC_Logo.svg",
)

export const JEMOREApp = new WorkData(
  20220727,
  false,
  false,
  "JEMORE App",
  "jemore-app",
  "...",
  "...",
  "Mobile App",
  "https://i.imgur.com/XATCJuR.png",
  [
    "Flutter",
    "Dart",
    "Parse",
  ],
  "An innovative and powerful mobile application ",
  "available on the Play Store. ",
  "This cutting-edge app was designed to revolutionize meeting management and participation at JEMORE. With a focus on convenience and anonymity, the \"JEMORE App\" allows users to easily confirm their presence at meetings and cast anonymous votes on crucial matters. ",
  "",
  [
    "https://i.imgur.com/XATCJuR.png",
    "https://i.imgur.com/PSJvptV.png",
  ],
  "https://play.google.com/store/apps/details?id=it.jemore.jemore_services",
  "https://avatars.githubusercontent.com/u/102101278",
)

export const JEMORETreasury = new WorkData(
  20220803,
  false,
  false,
  "JEMORE Treasury",
  "jemore-treasury",
  "...",
  "...",
  "Website",
  "https://i.imgur.com/NpWRniN.png",
  [
    "Flutter",
    "Dart",
  ],
  "An internal project that reflects my valuable contributions during my time at JEMORE. This specialized project was ",
  "designed to streamline and enhance ",
  "the treasury management processes within the organization. ",
  "",
  [
    "https://i.imgur.com/NpWRniN.png",
    "https://i.imgur.com/MieVdCy.png",
    "https://i.imgur.com/PXnXte4.png",
    "https://i.imgur.com/Ri4sx8S.png",
  ],
  undefined,
  "https://avatars.githubusercontent.com/u/102101278",
)

export const SQLServerDatabase = new WorkData(
  20220000,
  false,
  false,
  "SQL Server Database",
  "sql-database",
  "...",
  "...",
  "Database",
  "https://i.imgur.com/l9hWzLi.png",
  ["SQL Server"],
  "A crucial upgrade that revolutionized a client's data management system. Tasked with modernizing the client's server from an outdated language to the ",
  "more efficient and robust SQL.",
  "",
  "",
  [
    "https://i.imgur.com/l9hWzLi.png",
  ],
  undefined,
  "https://avatars.githubusercontent.com/u/102101278",
)

export const ChessSoftware = new WorkData(
  20221211,
  false,
  false,
  "Chess",
  "chess",
  "...",
  "...",
  "Desktop Game",
  "https://i.imgur.com/BfPrqrh.png",
  ["Java"],
  "Strategically crafted masterpiece that serves as a playground for exploring and implementing ",
  "SOLID principles. With a passion for clean and maintainable code, I embarked on this project to ensure that each aspect of the game adheres to SOLID design principles. ",
  "",
  "",
  [
    "https://i.imgur.com/BfPrqrh.png",
    "https://i.imgur.com/xzaisCW.png",
  ],
  "https://github.com/ZiClaud/Chess",
)

export const FightingGame = new WorkData(
  20221031,
  false,
  false,
  "Fighting Game",
  "fighting-game",
  "...",
  "...",
  "Desktop Game",
  "https://i.imgur.com/3fQrf61.png",
  ["Java"],
  "An adrenaline-pumping adventure that marks my first foray into the world of game development using Java. Embrace the thrill as you step into the virtual arena, engaging in intense battles with ",
  "computer-controlled opponents. ",
  "Armed with Java's power and flexibility, I crafted this game with passion and determination, learning valuable lessons in ",
  "game mechanics, graphics rendering, and user interaction.",
  [
    "https://i.imgur.com/3fQrf61.png",
  ],
  "https://github.com/ZiClaud/Fighting-Game",
)

export const PickyEater = new WorkData(
  20220510,
  false,
  false,
  "Picky Eater",
  "picky-eater",
  "...",
  "...",
  "Desktop App",
  "https://i.imgur.com/dRxlxf2.png",
  ["Java"],
  "A collaborative masterpiece and a memorable university project. Teaming up with Federico Matarante, we embarked on a journey into the realm of Java programming and Object-Oriented Programming (OOP). This Desktop Application ",
  "was designed to cater to picky eaters, offering personalized meal recommendations based on individual preferences and dietary restrictions. ",
  "Through Picky Eater, I gained valuable insights into the power of OOP, mastering the art of creating robust and scalable code. ",
  "",
  [
    "https://i.imgur.com/ILeeONf.png",
    "https://i.imgur.com/iGmpND4.png",
    "https://i.imgur.com/Lm5P0e1.png",
    "https://i.imgur.com/2WxL41m.png",
    "https://i.imgur.com/dRxlxf2.png",
    "https://i.imgur.com/Ei186oz.png",
  ],
  "https://github.com/ZiClaud/Picky-Eater",
)

export const OldPortfolio = new WorkData(
  20221016,
  false,
  false,
  "Old Portfolio",
  "old-portfolio",
  "...",
  "...",
  "Website",
  "https://i.imgur.com/dA288Wb.png",
  [
    "HTML",
    "CSS",
    "JavaScript",
  ],
  "A significant milestone in my journey as a developer. It marks my first venture into the world of web development, ",
  "where I designed and crafted an online portfolio from scratch ",
  "using HTML, JavaScript, and CSS. Take a trip down memory lane and witness my initial steps in the dynamic world of web development with my old Portfolio. ",
  "",
  [
    "https://i.imgur.com/dA288Wb.png",
    "https://i.imgur.com/B92q59u.png",
    "https://i.imgur.com/UEgeKfc.png",
    "https://i.imgur.com/3V2L6kf.png",
  ],
  "https://claudiodimaioold.netlify.app/",
)

export const HangmanGame = new WorkData(
  20201204,
  false,
  false,
  "Hangman Game",
  "hangman",
  "...",
  "...",
  "Command Line Game",
  "https://i.imgur.com/tdtrOVx.png",
  ["C Language"],
  "Hangman is my debut project. This command-line-based hangman game was crafted ",
  "entirely in C. ",
  "It was made using the first programming language I learned. ",
  "",
  [
    "https://i.imgur.com/tdtrOVx.png",
    "https://i.imgur.com/FU85cY5.png",
  ],
  "https://github.com/ZiClaud/Hangman-C",
)


export const AllWorks = [
  // WeeksOfMyYear,
  DrivaliaWebsite,
  // LupusAmongUs,
  MaterialYouNewTab,
  Magium,
  SudokuSolver,
  // InfoWebApp,
  // GTEConverter,
  CosmicGateway,
  Iremi,
  JEIOM,
  OpenSource1,
  Portfolio,
  ReactTest2,
  ReactTest1,
  JEMOREApp,
  JEMORETreasury,
  SQLServerDatabase,
  ChessSoftware,
  FightingGame,
  PickyEater,
  OldPortfolio,
  HangmanGame,
]
