import WorkData from "@/basics/WorkData";

export const WorkNotFound = new WorkData(
    404,
    false,
    false,
    "404",
    "404",
    "",
    "",
    "",
    "",
    [],
    "",
    "",
    "",
    "",
    [],
    "",
);

export const IremiApp = new WorkData(
    20230318,
    true,
    true,
    "Iremi App",
    "iremi",
    "I developed this app entirely on my own, and it offers users a range of breathing exercises that are specifically designed to ",
    "promote relaxation and mindfulness.",
    "Mobile App",
    "https://i.imgur.com/eoEx6Tt.png?1",
    [
        "Flutter",
        "Dart",
        "Firebase",
    ],
    "Iremi is a mobile app designed to help users ",
    "combat anxiety through guided breathing exercises. ",
    "Using Flutter and Dart, I have created a simple and intuitive app that offers a variety of breathing exercises tailored to he users' needs. \nThe app also includes a progress tracker that allows users to monitor their breathing habits and ",
    "track their progress over time.",
    [""],
    "https://github.com/ZiClaud/Iremi-Breathing-App",
);

export const JEIOM = new WorkData(
    20220614,
    true,
    false,
    "JEIOM23",
    "jeiom",
    "I was part of a team that developed this website for the JEIOM 2023 event. Our goal was to create a platform that would enable users to ",
    "organize their schedule for the event in a single, user-friendly interface",
    "Website",
    "https://i.imgur.com/nu9WG4d.png",
    [
        "React",
        "Node",
        "TailwindCSS",
    ],
    "",
    "",
    "",
    "",
    [""],
    "www.jeiom23.com",
);

export const ReactTest2 = new WorkData(
    20230601,
    true,
    false,
    "React 2",
    "react2",
    "...",
    "...",
    "Website",
    "https://i.imgur.com/TXE0NFx.png",
    [
        "React",
        "Node",
        "TailwindCSS",
    ],
    "",
    "",
    "",
    "",
    [""],
    "https://github.com/ZiClaud/nextjs-tailwindcss-template",
);

export const ReactTest1 = new WorkData(
    20220528,
    true,
    false,
    "React 1",
    "react1",
    "...",
    "...",
    "Website",
    "https://i.imgur.com/8AXClU0.png",
    [
        "React",
        "Node",
        "TailwindCSS",
    ],
    "",
    "",
    "",
    "",
    [""],
    "https://github.com/EscanorTargaryen/dash2",
);

export const Portfolio = new WorkData(
    20230426,
    true,
    true,
    "This Portfolio",
    "portfolio",
    "I developed this portfolio, taking inspiration from a design found online, created first in ",
    "Flutter, then recreated in React.",
    "Website",
    "https://i.imgur.com/5yosKhp.png",
    [
        "React",
        "TailwindCSS",
    ],
    "",
    "",
    "",
    "",
    [""],
    "https://claudiodimaioflutter.netlify.app/",
);

export const JEMOREApp = new WorkData(
    20220727,
    false,
    false,
    "JEMORE App",
    "jemore_app",
    "Application ...",
    "",
    "Mobile App",
    "https://i.imgur.com/WrD3akd.png",
    [
        "Flutter",
        "Dart",
        "Parse",
    ],
    "",
    "",
    "",
    "",
    [""],
    "https://play.google.com/store/apps/details?id=it.jemore.jemore_services",
);

export const JEMORETreasury = new WorkData(
    20220803,
    false,
    false,
    "JEMORE Treasury",
    "jemore_treasury",
    "Website ...",
    "",
    "Website",
    "https://i.imgur.com/NpWRniN.png",
    [
        "Flutter",
        "Dart",
    ],
    "",
    "",
    "",
    "",
    [""],
    undefined,
);

export const SQLServerDatabase = new WorkData(
    0,
    false,
    false,
    "SQL Server Database",
    "sql_database",
    "Database ...",
    "",
    "Database",
    "https://i.imgur.com/l9hWzLi.png",
    ["SQL Server"],
    "",
    "",
    "",
    "",
    [""], undefined,
);

export const ChessSoftware = new WorkData(
    0,
    false,
    false,
    "Chess Software",
    "chess",
    "Desktop App that...",
    "",
    "Desktop Game",
    "https://i.imgur.com/BfPrqrh.png",
    ["Java"],
    "",
    "",
    "",
    "",
    [""],
    "https://github.com/ZiClaud/Chess",
);

export const FightingGame = new WorkData(
    0,
    false,
    false,
    "Fighting Game",
    "fighting_game",
    "Desktop Game that...",
    "",
    "Desktop Game",
    "https://i.imgur.com/3fQrf61.png",
    ["Java"],
    "",
    "",
    "",
    "",
    [""],
    "https://github.com/ZiClaud/FightingGame",
);

export const PickyEater = new WorkData(
    0,
    false,
    false,
    "Picky Eater",
    "picky_eater",
    "Desktop App that...",
    "",
    "Desktop App",
    "https://i.imgur.com/ILeeONf.png",
    ["Java"],
    "",
    "",
    "",
    "",
    [""],
    "https://github.com/ZiClaud/PickyEaterApp",
);

export const OldPortfolio = new WorkData(
    0,
    false,
    false,
    "Old Portfolio",
    "old_portfolio",
    "Website ...",
    "",
    "Website",
    "https://i.imgur.com/dA288Wb.png",
    [
        "HTML",
        "CSS",
        "JavaScript",
    ],
    "",
    "",
    "",
    "",
    [""],
    "https://claudiodimaioold.netlify.app/",
);

export const HangmanGame = new WorkData(
    20201204,
    false,
    false,
    "Hangman Game",
    "hangman",
    "Command line game that...",
    "",
    "Command Line Game",
    "https://i.imgur.com/tdtrOVx.png",
    ["C"],
    "",
    "",
    "",
    "",
    [""],
    "https://github.com/ZiClaud/Hangman_C",
);


export const AllWorks = [
    IremiApp,
    JEIOM,
    Portfolio,
    ReactTest2,
    ReactTest1,
    JEMOREApp,
    JEMORETreasury,
    SQLServerDatabase,
    ChessSoftware,
    FightingGame,
    PickyEater,
    OldPortfolio,
    HangmanGame,
];